###### VARIABLES (tokens, etc) ######
@nonAdminUserAccess=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMTU1MTcwLCJpYXQiOjE3NDAxNDQzNzAsImp0aSI6ImMzYTE5ZTIxMmUxZDRjOTc5MTVlYzA1ZWZmYzFhZGVmIiwidXNlcl9pZCI6Mn0.72FGRJMO8W67WBp5fr1o1GTLhauluez17VvSnG14MrQ

@adminUserAccess=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMTU1NTIzLCJpYXQiOjE3NDAxNDQ3MjMsImp0aSI6IjE0MjA1MTAyYzMwZTQ3MjdhN2FkNTU0NGNmOWE5ZGJjIiwidXNlcl9pZCI6MX0.KLV8a5TwWfpmRXrxTXo-9VkYILwMQOJrkwXA0QSf-Go
########################################################################################

### login1
### A custom auth backend are implemented EmailOrUsernameModelBackend
### to be able for user to login using username or email
POST https://127.0.0.1:8080/posts/users/login/ HTTP/1.1
Content-Type: application/json

{
    "identifier": "admin",
    "password": "A#123qqq"
}

### login2
### A custom auth backend are implemented EmailOrUsernameModelBackend
### to be able for user to login using username or email
POST https://127.0.0.1:8080/posts/users/login/ HTTP/1.1
Content-Type: application/json

{
    "identifier": "user10",
    "password": "passworD10#"
}


#################################### START ####################################################

### create comment
POST https://127.0.0.1:8080/posts/comments/ HTTP/1.1
Content-Type: application/json

{
    "text": "Riveting!",
    "author": 2,
    "post": 4
}


### fetch all comments
GET https://127.0.0.1:8080/posts/comments/ HTTP/1.1
Content-Type: application/json

### update comment by Id (as ModelViewset and DefaultRouter automatically used id in the url)
PUT https://127.0.0.1:8080/posts/comments/4/ HTTP/1.1
Content-Type: application/json

{
    "text": "What a good post!",
    "author": 1,
    "post": 2
}

### update comment by Id (as ModelViewset and DefaultRouter automatically used id in the url)
PATCH https://127.0.0.1:8080/posts/comments/4/ HTTP/1.1
Content-Type: application/json

{
    "text": "Boring!, nothing special about the post"
}

### delete comment by id
DELETE https://127.0.0.1:8080/posts/comments/3/ HTTP/1.1






