###### VARIABLES (tokens, etc) ######
@nonAdminUserAccess=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMjE3NTYyLCJpYXQiOjE3NDAyMDY3NjIsImp0aSI6IjE5YjI5MGYyMmZlMzQwM2Q4OWYxZDkxNGE0NDQyY2UwIiwidXNlcl9pZCI6Nn0.wpOoPvN4-p5wqxsLwblHGfWvxPJ7zzCPuKFxBQdoYRk
@adminUserAccess=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMjE2NjY0LCJpYXQiOjE3NDAyMDU4NjQsImp0aSI6IjEyNzFhODEyZjQ4ZTRhNDhhYjcwMDAxNmQyN2Y4NGEyIiwidXNlcl9pZCI6MX0.nOFHG0HA2wxa0Qe_CkYPk6HFGx8js-f8Xo5LVr8msQs

########################################################################################

### login1
### A custom auth backend are implemented EmailOrUsernameModelBackend
### to be able for user to login using username or email
POST https://127.0.0.1:8080/posts/users/login/ HTTP/1.1
Content-Type: application/json

{
    "identifier": "admin",
    "password": "A#123qqq"
}

### login2
### A custom auth backend are implemented EmailOrUsernameModelBackend
### to be able for user to login using username or email
POST https://127.0.0.1:8080/posts/users/login/ HTTP/1.1
Content-Type: application/json

{
    "identifier": "user2",
    "password": "passworD1#"
}


#################################### START ####################################################

### create comment
POST https://127.0.0.1:8080/posts/comments/ HTTP/1.1
Authorization: Bearer {{nonAdminUserAccess}}
Content-Type: application/json

{
    "post": 4, // post_id
    "content": "{content....}" 
}


### fetch all comments
GET https://127.0.0.1:8080/posts/comments/ HTTP/1.1
Content-Type: application/json

### retrieve specific comment
GET https://127.0.0.1:8080/posts/comments/2/ HTTP/1.1
Content-Type: application/json

### update comment by Id (as ModelViewset and DefaultRouter automatically used id in the url)
PUT https://127.0.0.1:8080/posts/comments/3/ HTTP/1.1
Content-Type: application/json

{
    "text": "What a good post!",
    "author": 1,
    "post": 2
}

### update comment by Id (as ModelViewset and DefaultRouter automatically used id in the url)
PATCH https://127.0.0.1:8080/posts/comments/4/ HTTP/1.1
Content-Type: application/json

{
    "text": "Boring!, nothing special about the post"
}

### delete comment by id
DELETE https://127.0.0.1:8080/posts/comments/3/ HTTP/1.1










