services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    ports:
      - 6432:5432 # port mapping to 6432
  
  pgbouncer:
    image: pgbouncer/pgbouncer
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:6432/mydatabase
      PGBOUNCER_USER: myuser
      PGBOUNCER_PASSWORD: mypassword
      PGBOUNCER_PORT: 6432
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
    depends_on:
      - postgres
    
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/cert.pem:/etc/nginx/cert.pem:ro # uncomment on https; comment when testing with Social Auth
      - ./ssl/key.pem:/etc/nginx/key.pem:ro # uncomment on https; comment when testing with Social Auth
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - app-network
  
  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: 'no'
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - app-network
  
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge