###### VARIABLES ######
@nonAdminUserAccess=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQyOTIzNzUzLCJpYXQiOjE3NDI5MTI5NTMsImp0aSI6ImVkMDc4NzFiNGRlZTQyNDdhZGIzYjljZmRkYTVhZmQzIiwidXNlcl9pZCI6MjB9.Q-QDgXgc0f9EimnQyvOAQRnY3eeSSOGQ0xK6qcGuCYw
@adminUserAccess=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQyOTA2NjY1LCJpYXQiOjE3NDI4OTU4NjUsImp0aSI6ImNlMGQ5MjZiY2YyZjQxMzA5ZDViODM5ZmY2YzE0NmMyIiwidXNlcl9pZCI6MX0.JgMomDaqTk4zEg2zJmfFMnEbwagq22mU4YWZDcoWCXc
###
@refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0MjA5NzA2NiwiaWF0IjoxNzQxNDkyMjY2LCJqdGkiOiI3ODk5YjA4YjQwNmE0N2FkYTQ1NzM0OThiZjZkYjY5MiIsInVzZXJfaWQiOjR9.fCJJi1Pl9sGdituSksv6gyHN23xyvpJLykbjMaasT24
########################################################################################

### login1
### A custom auth backend are implemented EmailOrUsernameModelBackend
### to be able for user to login using username or email
POST https://127.0.0.1:8080/posts/users/login/ HTTP/1.1
Content-Type: application/json

{
    "identifier": "admin",
    "password": "A!123zzz"
}
### login2
### A custom auth backend are implemented EmailOrUsernameModelBackend
### to be able for user to login using username or email
POST http://127.0.0.1:8000/posts/users/login/ HTTP/1.1
Content-Type: application/json

{
    "identifier": "user18",
    "password": "passworD1#"
}


### user by id
GET https://127.0.0.1:8080/posts/users/13/ HTTP/1.1
Authorization: Bearer {{adminUserAccess}}
Content-Type: application/json

### follows
GET https://127.0.0.1:8080/posts/follows/ HTTP/1.1
Authorization: Bearer {{adminUserAccess}}
Content-Type: application/json


### list all public posts 
GET https://127.0.0.1:8080/posts/posts/ HTTP/1.1
Content-Type: application/json


### Admin User Deletes a Post
DELETE http://127.0.0.1:8000/posts/posts/3/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{adminUserAccess}}


### All Comments
GET http://127.0.0.1:8000/posts/comments/ HTTP/1.1
Content-Type: application/json



### Admin User Deletes a Comment
DELETE http://127.0.0.1:8000/posts/comments/1/ HTTP/1.1
Authorization: Bearer {{adminUserAccess}}
Content-Type: application/json


### list all users 
GET http://127.0.0.1:8000/posts/users/ HTTP/1.1
Authorization: Bearer {{adminUserAccess}}
Content-Type: application/json

### Admin User Updates a User
PATCH http://127.0.0.1:8000/posts/users/3/ HTTP/1.1
Authorization: Bearer {{nonAdminUserAccess}}
Content-Type: application/json

{
    "username": "updated_user1"
}

### Regular User Deletes Own Post
DELETE http://127.0.0.1:8000/posts/posts/4/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{nonAdminUserAccess}}

### Regular User Deletes Another User's Post
DELETE http://127.0.0.1:8000/posts/posts/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{nonAdminUserAccess}}

### Regular User Deletes Another User's Comment
DELETE http://127.0.0.1:8000/posts/comments/2/ HTTP/1.1
Authorization: Bearer {{nonAdminUserAccess}}
Content-Type: application/json

### User accesses protected route
GET http://127.0.0.1:8000/posts/feed/ HTTP/1.1
Authorization: Bearer {{nonAdminUserAccess}}
Content-Type: application/json

### Gues accesses protected route
GET http://127.0.0.1:8000/posts/feed/ HTTP/1.1
Content-Type: application/json

### Public Post in Feed
GET http://127.0.0.1:8000/posts/feed/ HTTP/1.1
Authorization: Bearer {{adminUserAccess}}
Content-Type: application/json

### Private Post Visibility (Owner)
GET http://127.0.0.1:8000/posts/posts/6/ HTTP/1.1
Authorization: Bearer {{nonAdminUserAccess}}
Content-Type: application/json

### Private Post Visibility (Other User)
GET http://127.0.0.1:8000/posts/posts/6/ HTTP/1.1
Authorization: Bearer {{nonAdminUserAccess}}
Content-Type: application/json