###### VARIABLES (tokens, etc) ######
@nonAdminUserAccess=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwODE5NzM3LCJpYXQiOjE3NDA4MDg5MzcsImp0aSI6ImVhMDVhMGFmNjczOTQ2ZmM5NGVkM2E3MTI4ODE2YTZmIiwidXNlcl9pZCI6NH0.9OlKEWsbZ4YAlyJitgqBPFDBbuGBZ_8nh7Wy3dlzaHA
@adminUserAccess=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMjEzNDY0LCJpYXQiOjE3NDAyMDI2NjQsImp0aSI6ImZkNTk0Y2ZmNDUwNzQ3NDlhYzUyZWFiNTI4YTAxZmU3IiwidXNlcl9pZCI6MX0.IIRvZ-ZykLZk6CeGDnDFtoep-xD5tboTA6u1qlfd6KA
########################################################################################

### login1
### A custom auth backend are implemented EmailOrUsernameModelBackend
### to be able for user to login using username or email
POST https://127.0.0.1:8080/posts/users/login/ HTTP/1.1
Content-Type: application/json

{
    "identifier": "admin",
    "password": "A#123qqq"
}

### login2
### A custom auth backend are implemented EmailOrUsernameModelBackend
### to be able for user to login using username or email
POST https://127.0.0.1:8080/posts/users/login/ HTTP/1.1
Content-Type: application/json

{
    "identifier": "user2",
    "password": "passworD1#"
}

#################################### START ####################################################


### create new post
POST https://127.0.0.1:8080/posts/posts/ HTTP/1.1
Authorization: Bearer {{nonAdminUserAccess}}
Content-Type: application/json

{
    "content": "Talk show host"
}

### list all posts - Public
GET https://127.0.0.1:8080/posts/posts/ HTTP/1.1
Content-Type: application/json

### update post by Id - Owner/author
PUT https://127.0.0.1:8080/posts/posts/1/ HTTP/1.1
Authorization: Bearer {{nonAdminUserAccess}}
Content-Type: application/json

{
    "content": "Hello, World!"
}

### update post by id - Owner/Author
PATCH https://127.0.0.1:8080/posts/posts/1/ HTTP/1.1 
Authorization: Bearer {{nonAdminUserAccess}}
Content-Type: application/json


### delete post by id - Owner/author
DELETE https://127.0.0.1:8080/posts/posts/1/ HTTP/1.1
Authorization: Bearer {{nonAdminUserAccess}}

### Fetch post by id - Public
GET https://127.0.0.1:8080/posts/posts/5/ HTTP/1.1 
Content-Type: application/json


### user commenting on a specific post
POST https://127.0.0.1:8080/posts/posts/5/comment/ HTTP/1.1 
Authorization: Bearer {{nonAdminUserAccess}}
Content-Type: application/json

{
    "content": "Riveting!"
}

### liking a post with pk 6; current user with pk 4
POST https://127.0.0.1:8080/posts/posts/6/like/ HTTP/1.1
Authorization: Bearer {{nonAdminUserAccess}}
Content-Type: application/json
