# Generated by Django 5.1.4 on 2025-03-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_privacy_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('user', 'User'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
